[package]
name = "tiangong-entry"
version.workspace = true
edition = "2024"
license = "Apache-2.0"

[dependencies]
tiangong-core = { workspace = true }
tiangong-plugin-mcp-protocol = { workspace = true }
tiangong-config = { workspace = true }
tiangong-plugin-runtime = { workspace = true }
tiangong-cli = { workspace = true }
tiangong-server = { workspace = true }
tiangong-bots = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
reqwest = { workspace = true, default-features = false, features = ["blocking", "json", "rustls"] }
semver = { workspace = true }
minisign-verify = "0.2"
base64 = { workspace = true }
tokio = { workspace = true, features = ["rt", "time", "sync", "net"] }
libc = { workspace = true }
